#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="MES_VINA")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertITEM_INFO(ITEM_INFO instance);
    partial void UpdateITEM_INFO(ITEM_INFO instance);
    partial void DeleteITEM_INFO(ITEM_INFO instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::WindowsFormsApp1.Properties.Settings.Default.MES_VINAConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ITEM_INFO> ITEM_INFOs
		{
			get
			{
				return this.GetTable<ITEM_INFO>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ITEM_INFO")]
	public partial class ITEM_INFO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ITEM_ID;
		
		private string _ASSET_TYPE;
		
		private string _ITEM_CODE;
		
		private string _ITEM_NAME;
		
		private string _PURC_NAME;
		
		private string _MAIN_DRAWING_NO;
		
		private string _DRAWING_NO;
		
		private string _BUSINESS_LCODE;
		
		private string _PRODUCT_FAMILY;
		
		private string _PRODUCT_TYPE;
		
		private string _PIN;
		
		private string _TYPE;
		
		private string _PITCH;
		
		private string _PART_TYPE;
		
		private System.Nullable<decimal> _PILLAR;
		
		private System.Nullable<decimal> _AREA;
		
		private string _REVISION;
		
		private string _REVISION_PROD;
		
		private string _DEVICE_GROUP;
		
		private string _COMPO_FLAG;
		
		private string _MAIN_SITE;
		
		private string _SC_PROCESS;
		
		private System.Nullable<decimal> _THICKNESS;
		
		private string _MIX_CODE;
		
		private string _UNIT;
		
		private System.Nullable<decimal> _PARA_QTY;
		
		private string _JIG_YN;
		
		private string _MATERIAL_CODE;
		
		private string _MEASUREMENT;
		
		private string _CUST_LTYPE;
		
		private string _SPECIAL_ITEM_YN;
		
		private string _SPECIAL_REMARK;
		
		private string _SEND_DRAWING;
		
		private string _DRAWING_PDF_URL;
		
		private string _DRAWING_DWG_URL;
		
		private string _DRAWING_3DPDF_URL;
		
		private string _BOM_APPROVAL;
		
		private string _BOM_APPROVER;
		
		private System.Nullable<System.DateTime> _BOM_APPROVAL_DATE;
		
		private string _PURC_TYPE1;
		
		private string _REQ_YN;
		
		private string _USE_YN;
		
		private string _REMARK;
		
		private string _P_CODE;
		
		private System.Nullable<System.DateTime> _MODY_DATE;
		
		private string _MODY_USERID;
		
		private string _MODY_IP_ADDR;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnITEM_IDChanging(string value);
    partial void OnITEM_IDChanged();
    partial void OnASSET_TYPEChanging(string value);
    partial void OnASSET_TYPEChanged();
    partial void OnITEM_CODEChanging(string value);
    partial void OnITEM_CODEChanged();
    partial void OnITEM_NAMEChanging(string value);
    partial void OnITEM_NAMEChanged();
    partial void OnPURC_NAMEChanging(string value);
    partial void OnPURC_NAMEChanged();
    partial void OnMAIN_DRAWING_NOChanging(string value);
    partial void OnMAIN_DRAWING_NOChanged();
    partial void OnDRAWING_NOChanging(string value);
    partial void OnDRAWING_NOChanged();
    partial void OnBUSINESS_LCODEChanging(string value);
    partial void OnBUSINESS_LCODEChanged();
    partial void OnPRODUCT_FAMILYChanging(string value);
    partial void OnPRODUCT_FAMILYChanged();
    partial void OnPRODUCT_TYPEChanging(string value);
    partial void OnPRODUCT_TYPEChanged();
    partial void OnPINChanging(string value);
    partial void OnPINChanged();
    partial void OnTYPEChanging(string value);
    partial void OnTYPEChanged();
    partial void OnPITCHChanging(string value);
    partial void OnPITCHChanged();
    partial void OnPART_TYPEChanging(string value);
    partial void OnPART_TYPEChanged();
    partial void OnPILLARChanging(System.Nullable<decimal> value);
    partial void OnPILLARChanged();
    partial void OnAREAChanging(System.Nullable<decimal> value);
    partial void OnAREAChanged();
    partial void OnREVISIONChanging(string value);
    partial void OnREVISIONChanged();
    partial void OnREVISION_PRODChanging(string value);
    partial void OnREVISION_PRODChanged();
    partial void OnDEVICE_GROUPChanging(string value);
    partial void OnDEVICE_GROUPChanged();
    partial void OnCOMPO_FLAGChanging(string value);
    partial void OnCOMPO_FLAGChanged();
    partial void OnMAIN_SITEChanging(string value);
    partial void OnMAIN_SITEChanged();
    partial void OnSC_PROCESSChanging(string value);
    partial void OnSC_PROCESSChanged();
    partial void OnTHICKNESSChanging(System.Nullable<decimal> value);
    partial void OnTHICKNESSChanged();
    partial void OnMIX_CODEChanging(string value);
    partial void OnMIX_CODEChanged();
    partial void OnUNITChanging(string value);
    partial void OnUNITChanged();
    partial void OnPARA_QTYChanging(System.Nullable<decimal> value);
    partial void OnPARA_QTYChanged();
    partial void OnJIG_YNChanging(string value);
    partial void OnJIG_YNChanged();
    partial void OnMATERIAL_CODEChanging(string value);
    partial void OnMATERIAL_CODEChanged();
    partial void OnMEASUREMENTChanging(string value);
    partial void OnMEASUREMENTChanged();
    partial void OnCUST_LTYPEChanging(string value);
    partial void OnCUST_LTYPEChanged();
    partial void OnSPECIAL_ITEM_YNChanging(string value);
    partial void OnSPECIAL_ITEM_YNChanged();
    partial void OnSPECIAL_REMARKChanging(string value);
    partial void OnSPECIAL_REMARKChanged();
    partial void OnSEND_DRAWINGChanging(string value);
    partial void OnSEND_DRAWINGChanged();
    partial void OnDRAWING_PDF_URLChanging(string value);
    partial void OnDRAWING_PDF_URLChanged();
    partial void OnDRAWING_DWG_URLChanging(string value);
    partial void OnDRAWING_DWG_URLChanged();
    partial void OnDRAWING_3DPDF_URLChanging(string value);
    partial void OnDRAWING_3DPDF_URLChanged();
    partial void OnBOM_APPROVALChanging(string value);
    partial void OnBOM_APPROVALChanged();
    partial void OnBOM_APPROVERChanging(string value);
    partial void OnBOM_APPROVERChanged();
    partial void OnBOM_APPROVAL_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnBOM_APPROVAL_DATEChanged();
    partial void OnPURC_TYPE1Changing(string value);
    partial void OnPURC_TYPE1Changed();
    partial void OnREQ_YNChanging(string value);
    partial void OnREQ_YNChanged();
    partial void OnUSE_YNChanging(string value);
    partial void OnUSE_YNChanged();
    partial void OnREMARKChanging(string value);
    partial void OnREMARKChanged();
    partial void OnP_CODEChanging(string value);
    partial void OnP_CODEChanged();
    partial void OnMODY_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnMODY_DATEChanged();
    partial void OnMODY_USERIDChanging(string value);
    partial void OnMODY_USERIDChanged();
    partial void OnMODY_IP_ADDRChanging(string value);
    partial void OnMODY_IP_ADDRChanged();
    #endregion
		
		public ITEM_INFO()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ITEM_ID", DbType="VarChar(6) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ITEM_ID
		{
			get
			{
				return this._ITEM_ID;
			}
			set
			{
				if ((this._ITEM_ID != value))
				{
					this.OnITEM_IDChanging(value);
					this.SendPropertyChanging();
					this._ITEM_ID = value;
					this.SendPropertyChanged("ITEM_ID");
					this.OnITEM_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ASSET_TYPE", DbType="VarChar(10)")]
		public string ASSET_TYPE
		{
			get
			{
				return this._ASSET_TYPE;
			}
			set
			{
				if ((this._ASSET_TYPE != value))
				{
					this.OnASSET_TYPEChanging(value);
					this.SendPropertyChanging();
					this._ASSET_TYPE = value;
					this.SendPropertyChanged("ASSET_TYPE");
					this.OnASSET_TYPEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ITEM_CODE", DbType="VarChar(100)")]
		public string ITEM_CODE
		{
			get
			{
				return this._ITEM_CODE;
			}
			set
			{
				if ((this._ITEM_CODE != value))
				{
					this.OnITEM_CODEChanging(value);
					this.SendPropertyChanging();
					this._ITEM_CODE = value;
					this.SendPropertyChanged("ITEM_CODE");
					this.OnITEM_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ITEM_NAME", DbType="NVarChar(200)")]
		public string ITEM_NAME
		{
			get
			{
				return this._ITEM_NAME;
			}
			set
			{
				if ((this._ITEM_NAME != value))
				{
					this.OnITEM_NAMEChanging(value);
					this.SendPropertyChanging();
					this._ITEM_NAME = value;
					this.SendPropertyChanged("ITEM_NAME");
					this.OnITEM_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PURC_NAME", DbType="NVarChar(200)")]
		public string PURC_NAME
		{
			get
			{
				return this._PURC_NAME;
			}
			set
			{
				if ((this._PURC_NAME != value))
				{
					this.OnPURC_NAMEChanging(value);
					this.SendPropertyChanging();
					this._PURC_NAME = value;
					this.SendPropertyChanged("PURC_NAME");
					this.OnPURC_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAIN_DRAWING_NO", DbType="VarChar(30)")]
		public string MAIN_DRAWING_NO
		{
			get
			{
				return this._MAIN_DRAWING_NO;
			}
			set
			{
				if ((this._MAIN_DRAWING_NO != value))
				{
					this.OnMAIN_DRAWING_NOChanging(value);
					this.SendPropertyChanging();
					this._MAIN_DRAWING_NO = value;
					this.SendPropertyChanged("MAIN_DRAWING_NO");
					this.OnMAIN_DRAWING_NOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DRAWING_NO", DbType="VarChar(50)")]
		public string DRAWING_NO
		{
			get
			{
				return this._DRAWING_NO;
			}
			set
			{
				if ((this._DRAWING_NO != value))
				{
					this.OnDRAWING_NOChanging(value);
					this.SendPropertyChanging();
					this._DRAWING_NO = value;
					this.SendPropertyChanged("DRAWING_NO");
					this.OnDRAWING_NOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BUSINESS_LCODE", DbType="VarChar(10)")]
		public string BUSINESS_LCODE
		{
			get
			{
				return this._BUSINESS_LCODE;
			}
			set
			{
				if ((this._BUSINESS_LCODE != value))
				{
					this.OnBUSINESS_LCODEChanging(value);
					this.SendPropertyChanging();
					this._BUSINESS_LCODE = value;
					this.SendPropertyChanged("BUSINESS_LCODE");
					this.OnBUSINESS_LCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRODUCT_FAMILY", DbType="VarChar(10)")]
		public string PRODUCT_FAMILY
		{
			get
			{
				return this._PRODUCT_FAMILY;
			}
			set
			{
				if ((this._PRODUCT_FAMILY != value))
				{
					this.OnPRODUCT_FAMILYChanging(value);
					this.SendPropertyChanging();
					this._PRODUCT_FAMILY = value;
					this.SendPropertyChanged("PRODUCT_FAMILY");
					this.OnPRODUCT_FAMILYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRODUCT_TYPE", DbType="VarChar(10)")]
		public string PRODUCT_TYPE
		{
			get
			{
				return this._PRODUCT_TYPE;
			}
			set
			{
				if ((this._PRODUCT_TYPE != value))
				{
					this.OnPRODUCT_TYPEChanging(value);
					this.SendPropertyChanging();
					this._PRODUCT_TYPE = value;
					this.SendPropertyChanged("PRODUCT_TYPE");
					this.OnPRODUCT_TYPEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PIN", DbType="VarChar(5)")]
		public string PIN
		{
			get
			{
				return this._PIN;
			}
			set
			{
				if ((this._PIN != value))
				{
					this.OnPINChanging(value);
					this.SendPropertyChanging();
					this._PIN = value;
					this.SendPropertyChanged("PIN");
					this.OnPINChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TYPE", DbType="VarChar(10)")]
		public string TYPE
		{
			get
			{
				return this._TYPE;
			}
			set
			{
				if ((this._TYPE != value))
				{
					this.OnTYPEChanging(value);
					this.SendPropertyChanging();
					this._TYPE = value;
					this.SendPropertyChanged("TYPE");
					this.OnTYPEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PITCH", DbType="VarChar(10)")]
		public string PITCH
		{
			get
			{
				return this._PITCH;
			}
			set
			{
				if ((this._PITCH != value))
				{
					this.OnPITCHChanging(value);
					this.SendPropertyChanging();
					this._PITCH = value;
					this.SendPropertyChanged("PITCH");
					this.OnPITCHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PART_TYPE", DbType="VarChar(10)")]
		public string PART_TYPE
		{
			get
			{
				return this._PART_TYPE;
			}
			set
			{
				if ((this._PART_TYPE != value))
				{
					this.OnPART_TYPEChanging(value);
					this.SendPropertyChanging();
					this._PART_TYPE = value;
					this.SendPropertyChanged("PART_TYPE");
					this.OnPART_TYPEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PILLAR", DbType="Decimal(14,4)")]
		public System.Nullable<decimal> PILLAR
		{
			get
			{
				return this._PILLAR;
			}
			set
			{
				if ((this._PILLAR != value))
				{
					this.OnPILLARChanging(value);
					this.SendPropertyChanging();
					this._PILLAR = value;
					this.SendPropertyChanged("PILLAR");
					this.OnPILLARChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AREA", DbType="Decimal(14,4)")]
		public System.Nullable<decimal> AREA
		{
			get
			{
				return this._AREA;
			}
			set
			{
				if ((this._AREA != value))
				{
					this.OnAREAChanging(value);
					this.SendPropertyChanging();
					this._AREA = value;
					this.SendPropertyChanged("AREA");
					this.OnAREAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REVISION", DbType="VarChar(1)")]
		public string REVISION
		{
			get
			{
				return this._REVISION;
			}
			set
			{
				if ((this._REVISION != value))
				{
					this.OnREVISIONChanging(value);
					this.SendPropertyChanging();
					this._REVISION = value;
					this.SendPropertyChanged("REVISION");
					this.OnREVISIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REVISION_PROD", DbType="VarChar(2)")]
		public string REVISION_PROD
		{
			get
			{
				return this._REVISION_PROD;
			}
			set
			{
				if ((this._REVISION_PROD != value))
				{
					this.OnREVISION_PRODChanging(value);
					this.SendPropertyChanging();
					this._REVISION_PROD = value;
					this.SendPropertyChanged("REVISION_PROD");
					this.OnREVISION_PRODChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEVICE_GROUP", DbType="VarChar(10)")]
		public string DEVICE_GROUP
		{
			get
			{
				return this._DEVICE_GROUP;
			}
			set
			{
				if ((this._DEVICE_GROUP != value))
				{
					this.OnDEVICE_GROUPChanging(value);
					this.SendPropertyChanging();
					this._DEVICE_GROUP = value;
					this.SendPropertyChanged("DEVICE_GROUP");
					this.OnDEVICE_GROUPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COMPO_FLAG", DbType="VarChar(10)")]
		public string COMPO_FLAG
		{
			get
			{
				return this._COMPO_FLAG;
			}
			set
			{
				if ((this._COMPO_FLAG != value))
				{
					this.OnCOMPO_FLAGChanging(value);
					this.SendPropertyChanging();
					this._COMPO_FLAG = value;
					this.SendPropertyChanged("COMPO_FLAG");
					this.OnCOMPO_FLAGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAIN_SITE", DbType="VarChar(10)")]
		public string MAIN_SITE
		{
			get
			{
				return this._MAIN_SITE;
			}
			set
			{
				if ((this._MAIN_SITE != value))
				{
					this.OnMAIN_SITEChanging(value);
					this.SendPropertyChanging();
					this._MAIN_SITE = value;
					this.SendPropertyChanged("MAIN_SITE");
					this.OnMAIN_SITEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SC_PROCESS", DbType="VarChar(10)")]
		public string SC_PROCESS
		{
			get
			{
				return this._SC_PROCESS;
			}
			set
			{
				if ((this._SC_PROCESS != value))
				{
					this.OnSC_PROCESSChanging(value);
					this.SendPropertyChanging();
					this._SC_PROCESS = value;
					this.SendPropertyChanged("SC_PROCESS");
					this.OnSC_PROCESSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_THICKNESS", DbType="Decimal(14,4)")]
		public System.Nullable<decimal> THICKNESS
		{
			get
			{
				return this._THICKNESS;
			}
			set
			{
				if ((this._THICKNESS != value))
				{
					this.OnTHICKNESSChanging(value);
					this.SendPropertyChanging();
					this._THICKNESS = value;
					this.SendPropertyChanged("THICKNESS");
					this.OnTHICKNESSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MIX_CODE", DbType="VarChar(30)")]
		public string MIX_CODE
		{
			get
			{
				return this._MIX_CODE;
			}
			set
			{
				if ((this._MIX_CODE != value))
				{
					this.OnMIX_CODEChanging(value);
					this.SendPropertyChanging();
					this._MIX_CODE = value;
					this.SendPropertyChanged("MIX_CODE");
					this.OnMIX_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UNIT", DbType="VarChar(10)")]
		public string UNIT
		{
			get
			{
				return this._UNIT;
			}
			set
			{
				if ((this._UNIT != value))
				{
					this.OnUNITChanging(value);
					this.SendPropertyChanging();
					this._UNIT = value;
					this.SendPropertyChanged("UNIT");
					this.OnUNITChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PARA_QTY", DbType="Decimal(14,4)")]
		public System.Nullable<decimal> PARA_QTY
		{
			get
			{
				return this._PARA_QTY;
			}
			set
			{
				if ((this._PARA_QTY != value))
				{
					this.OnPARA_QTYChanging(value);
					this.SendPropertyChanging();
					this._PARA_QTY = value;
					this.SendPropertyChanged("PARA_QTY");
					this.OnPARA_QTYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JIG_YN", DbType="VarChar(1)")]
		public string JIG_YN
		{
			get
			{
				return this._JIG_YN;
			}
			set
			{
				if ((this._JIG_YN != value))
				{
					this.OnJIG_YNChanging(value);
					this.SendPropertyChanging();
					this._JIG_YN = value;
					this.SendPropertyChanged("JIG_YN");
					this.OnJIG_YNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATERIAL_CODE", DbType="VarChar(10)")]
		public string MATERIAL_CODE
		{
			get
			{
				return this._MATERIAL_CODE;
			}
			set
			{
				if ((this._MATERIAL_CODE != value))
				{
					this.OnMATERIAL_CODEChanging(value);
					this.SendPropertyChanging();
					this._MATERIAL_CODE = value;
					this.SendPropertyChanged("MATERIAL_CODE");
					this.OnMATERIAL_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MEASUREMENT", DbType="VarChar(30)")]
		public string MEASUREMENT
		{
			get
			{
				return this._MEASUREMENT;
			}
			set
			{
				if ((this._MEASUREMENT != value))
				{
					this.OnMEASUREMENTChanging(value);
					this.SendPropertyChanging();
					this._MEASUREMENT = value;
					this.SendPropertyChanged("MEASUREMENT");
					this.OnMEASUREMENTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUST_LTYPE", DbType="VarChar(10)")]
		public string CUST_LTYPE
		{
			get
			{
				return this._CUST_LTYPE;
			}
			set
			{
				if ((this._CUST_LTYPE != value))
				{
					this.OnCUST_LTYPEChanging(value);
					this.SendPropertyChanging();
					this._CUST_LTYPE = value;
					this.SendPropertyChanged("CUST_LTYPE");
					this.OnCUST_LTYPEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SPECIAL_ITEM_YN", DbType="VarChar(1)")]
		public string SPECIAL_ITEM_YN
		{
			get
			{
				return this._SPECIAL_ITEM_YN;
			}
			set
			{
				if ((this._SPECIAL_ITEM_YN != value))
				{
					this.OnSPECIAL_ITEM_YNChanging(value);
					this.SendPropertyChanging();
					this._SPECIAL_ITEM_YN = value;
					this.SendPropertyChanged("SPECIAL_ITEM_YN");
					this.OnSPECIAL_ITEM_YNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SPECIAL_REMARK", DbType="NVarChar(500)")]
		public string SPECIAL_REMARK
		{
			get
			{
				return this._SPECIAL_REMARK;
			}
			set
			{
				if ((this._SPECIAL_REMARK != value))
				{
					this.OnSPECIAL_REMARKChanging(value);
					this.SendPropertyChanging();
					this._SPECIAL_REMARK = value;
					this.SendPropertyChanged("SPECIAL_REMARK");
					this.OnSPECIAL_REMARKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SEND_DRAWING", DbType="VarChar(30)")]
		public string SEND_DRAWING
		{
			get
			{
				return this._SEND_DRAWING;
			}
			set
			{
				if ((this._SEND_DRAWING != value))
				{
					this.OnSEND_DRAWINGChanging(value);
					this.SendPropertyChanging();
					this._SEND_DRAWING = value;
					this.SendPropertyChanged("SEND_DRAWING");
					this.OnSEND_DRAWINGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DRAWING_PDF_URL", DbType="NVarChar(200)")]
		public string DRAWING_PDF_URL
		{
			get
			{
				return this._DRAWING_PDF_URL;
			}
			set
			{
				if ((this._DRAWING_PDF_URL != value))
				{
					this.OnDRAWING_PDF_URLChanging(value);
					this.SendPropertyChanging();
					this._DRAWING_PDF_URL = value;
					this.SendPropertyChanged("DRAWING_PDF_URL");
					this.OnDRAWING_PDF_URLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DRAWING_DWG_URL", DbType="NVarChar(200)")]
		public string DRAWING_DWG_URL
		{
			get
			{
				return this._DRAWING_DWG_URL;
			}
			set
			{
				if ((this._DRAWING_DWG_URL != value))
				{
					this.OnDRAWING_DWG_URLChanging(value);
					this.SendPropertyChanging();
					this._DRAWING_DWG_URL = value;
					this.SendPropertyChanged("DRAWING_DWG_URL");
					this.OnDRAWING_DWG_URLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DRAWING_3DPDF_URL", DbType="NVarChar(200)")]
		public string DRAWING_3DPDF_URL
		{
			get
			{
				return this._DRAWING_3DPDF_URL;
			}
			set
			{
				if ((this._DRAWING_3DPDF_URL != value))
				{
					this.OnDRAWING_3DPDF_URLChanging(value);
					this.SendPropertyChanging();
					this._DRAWING_3DPDF_URL = value;
					this.SendPropertyChanged("DRAWING_3DPDF_URL");
					this.OnDRAWING_3DPDF_URLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BOM_APPROVAL", DbType="VarChar(1)")]
		public string BOM_APPROVAL
		{
			get
			{
				return this._BOM_APPROVAL;
			}
			set
			{
				if ((this._BOM_APPROVAL != value))
				{
					this.OnBOM_APPROVALChanging(value);
					this.SendPropertyChanging();
					this._BOM_APPROVAL = value;
					this.SendPropertyChanged("BOM_APPROVAL");
					this.OnBOM_APPROVALChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BOM_APPROVER", DbType="VarChar(15)")]
		public string BOM_APPROVER
		{
			get
			{
				return this._BOM_APPROVER;
			}
			set
			{
				if ((this._BOM_APPROVER != value))
				{
					this.OnBOM_APPROVERChanging(value);
					this.SendPropertyChanging();
					this._BOM_APPROVER = value;
					this.SendPropertyChanged("BOM_APPROVER");
					this.OnBOM_APPROVERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BOM_APPROVAL_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> BOM_APPROVAL_DATE
		{
			get
			{
				return this._BOM_APPROVAL_DATE;
			}
			set
			{
				if ((this._BOM_APPROVAL_DATE != value))
				{
					this.OnBOM_APPROVAL_DATEChanging(value);
					this.SendPropertyChanging();
					this._BOM_APPROVAL_DATE = value;
					this.SendPropertyChanged("BOM_APPROVAL_DATE");
					this.OnBOM_APPROVAL_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PURC_TYPE1", DbType="VarChar(10)")]
		public string PURC_TYPE1
		{
			get
			{
				return this._PURC_TYPE1;
			}
			set
			{
				if ((this._PURC_TYPE1 != value))
				{
					this.OnPURC_TYPE1Changing(value);
					this.SendPropertyChanging();
					this._PURC_TYPE1 = value;
					this.SendPropertyChanged("PURC_TYPE1");
					this.OnPURC_TYPE1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REQ_YN", DbType="VarChar(1)")]
		public string REQ_YN
		{
			get
			{
				return this._REQ_YN;
			}
			set
			{
				if ((this._REQ_YN != value))
				{
					this.OnREQ_YNChanging(value);
					this.SendPropertyChanging();
					this._REQ_YN = value;
					this.SendPropertyChanged("REQ_YN");
					this.OnREQ_YNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USE_YN", DbType="VarChar(1)")]
		public string USE_YN
		{
			get
			{
				return this._USE_YN;
			}
			set
			{
				if ((this._USE_YN != value))
				{
					this.OnUSE_YNChanging(value);
					this.SendPropertyChanging();
					this._USE_YN = value;
					this.SendPropertyChanged("USE_YN");
					this.OnUSE_YNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REMARK", DbType="NVarChar(200)")]
		public string REMARK
		{
			get
			{
				return this._REMARK;
			}
			set
			{
				if ((this._REMARK != value))
				{
					this.OnREMARKChanging(value);
					this.SendPropertyChanging();
					this._REMARK = value;
					this.SendPropertyChanged("REMARK");
					this.OnREMARKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P_CODE", DbType="VarChar(2)")]
		public string P_CODE
		{
			get
			{
				return this._P_CODE;
			}
			set
			{
				if ((this._P_CODE != value))
				{
					this.OnP_CODEChanging(value);
					this.SendPropertyChanging();
					this._P_CODE = value;
					this.SendPropertyChanged("P_CODE");
					this.OnP_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MODY_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> MODY_DATE
		{
			get
			{
				return this._MODY_DATE;
			}
			set
			{
				if ((this._MODY_DATE != value))
				{
					this.OnMODY_DATEChanging(value);
					this.SendPropertyChanging();
					this._MODY_DATE = value;
					this.SendPropertyChanged("MODY_DATE");
					this.OnMODY_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MODY_USERID", DbType="VarChar(15)")]
		public string MODY_USERID
		{
			get
			{
				return this._MODY_USERID;
			}
			set
			{
				if ((this._MODY_USERID != value))
				{
					this.OnMODY_USERIDChanging(value);
					this.SendPropertyChanging();
					this._MODY_USERID = value;
					this.SendPropertyChanged("MODY_USERID");
					this.OnMODY_USERIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MODY_IP_ADDR", DbType="VarChar(50)")]
		public string MODY_IP_ADDR
		{
			get
			{
				return this._MODY_IP_ADDR;
			}
			set
			{
				if ((this._MODY_IP_ADDR != value))
				{
					this.OnMODY_IP_ADDRChanging(value);
					this.SendPropertyChanging();
					this._MODY_IP_ADDR = value;
					this.SendPropertyChanged("MODY_IP_ADDR");
					this.OnMODY_IP_ADDRChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
