using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using static WindowsFormsApp1.Helper;

namespace AutoGeneratedClass
{
    public partial class InfoColum
    {
        public string ColumName { get; set; }
        public string TypeName { get; set; }
        public bool IsNull { get; set; }
        public bool OnChanged { get; set; }
        public bool IsShow { get; set; }
        public bool IsVNull { get; set; }
        public bool IsVDouble { get; set; }
        public bool IsCopyUpdate { get; set; }
        public bool IsAddBinding { get; set; }
        public ControlType ControlType { get; set; }
        public string TextControl { get; set; }
        public string Tooltip { get; set; }
        public int MaxLen { get; set; }
        public string ServiceReference { get; set; }
        public bool ServiceReferenceAdd { get; set; }
        public bool ServiceReferenceUpdate { get; set; }
        public bool ServiceReferenceRemove { get; set; }
        public bool IsFind { get; set; }
        public InfoColum() {
            ControlType = ControlType.TextBox;
        }
    }
}
